#开发环境配置
server:
  port: 8088

#spring
spring:
  devtools:
    restart:
      enabled: true
  application:
    name: redis-demo
  redis:
    database: 1          # Redis数据库索引（默认为0）
    timeout: 0            # 连接超时时间（毫秒）
    host: 36.155.115.153
    port: 6379
    password: 123456
    jedis:
      pool:
        max-idle: 10
        max-active: 10      # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 1000      # 连接池最大阻塞等待时间（使用负值表示没有限制）